_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types: null

scenario_tokens: 
  - a52bdf88b5b75aff # Lattice-IDM doing good
  - 5db9949de5975ffd # Lattice-IDM doing good
  - 7bc40ece02025fd7 # Lattice-IDM doing good
  - 49db2d18c6dc554a # Lattice-IDM doing good
  - 542b953f57c35e4a # Lattice-IDM doing good
  - 3f62b73f3b8d527b # Lattice-IDM doing good
  - 34ac5c7f439b561a # Lattice-IDM doing good
  - 348ec23d22855898 # Lattice-IDM doing good
  - b8d925e54e6f5a8f # Lattice-IDM doing good
  - 0a9404513dcc54f2 # Lattice-IDM doing good
  - 93a905027499542c # Lattice-IDM doing good
  - b7e64de3350e5118 # Lattice-IDM doing good
  - 52bd18c9f5db513a # Lattice-IDM doing good
  - b52c963ae9175824 # Lattice-IDM doing good
  - c881b474ecc256ac # Lattice-IDM doing good
  - e0a1e16982695139 # Lattice-IDM doing good
  

log_names: null                         # Filter scenarios by log names
map_names: null                        # Filter scenarios by map names



num_scenarios_per_type: null        # Number of scenarios per type
limit_total_scenarios: null         # Limit total scenarios (float = fraction, int = num) - this filter can be applied on top of num_scenarios_per_type
timestamp_threshold_s: null         # Filter scenarios to ensure scenarios have more than `timestamp_threshold_s` seconds between their initial lidar timestamps
ego_displacement_minimum_m: null    # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold: null     # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold: null      # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance: null         # Value at or below which a speed change between two timepoints should be ignored as noise.


expand_scenarios: false             # Whether to expand multi-sample scenarios to multiple single-sample scenarios
remove_invalid_goals: false         # Whether to remove scenarios where the mission goal is invalid
shuffle: false      