

python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_pdm.py \
+simulation=closed_loop_nonreactive_agents \
planner=pdm_closed_planner \
scenario_filter=SuperHard \
scenario_builder=nuplan_mini \
hydra.searchpath="[pkg://tuplan_garage.planning.script.config.common, pkg://tuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]"




python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_pdm.py \
+simulation=closed_loop_reactive_agents \
planner=planTF \
scenario_filter=Hard \
scenario_builder=nuplan_mini \
experiment_uid=$SPLIT/$PLANNER \
planner.imitation_planner.planner_ckpt="$CKPT_ROOT/$PLANNER.ckpt"

python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_pdm.py \
+simulation=closed_loop_reactive_agents \
planner=ml_planner \
model=urban_driver_open_loop_model \
scenario_filter=Hard \
scenario_builder=nuplan_mini \
planner.ml_planner.model_config=${model} \
planner.ml_planner.checkpoint_path="xxx.ckpt"